### ISSUE TITLE
script to convert svd files automatically

### ISSUE THREAD

**Issue by leommxj** [Accenture/FirmLoader#2]
Hi, are there any scripts that can be used to convert svd files to this metadata format? :)

**Comment by Martyx00** [comment]
You can try this: [firmloader_svdparse-master.zip](https://github.com/Accenture/FirmLoader/files/13239219/firmloader_svdparse-master.zip) (although not really officially published)

**Comment by leommxj** [comment]
> You can try this: [firmloader_svdparse-master.zip](https://github.com/Accenture/FirmLoader/files/13239219/firmloader_svdparse-master.zip) (although not really officially published)

thanks, I'll try this out.
